(() => {
  const $ = (id) => document.getElementById(id);
  const screens = { intro: $("introScreen"), game: $("gameScreen"), reveal: $("revealScreen") };
  const canvas = $("gameCanvas"), ctx = canvas.getContext("2d"), W = canvas.width, H = canvas.height;
  let game, soundOn = true, audioCtx;
  const blocksTemplate = [
    { x:120,y:185,treasure:"banana",hint:true }, { x:320,y:170,treasure:null },
    { x:570,y:205,treasure:"diamond",hint:true }, { x:560,y:435,treasure:"banana",hint:false },
    { x:155,y:560,treasure:"diamond",hint:true }, { x:350,y:575,treasure:null },
    { x:325,y:720,treasure:"banana",hint:true }, { x:555,y:740,treasure:"cake",hint:true },
    { x:95,y:730,treasure:null }, { x:655,y:650,treasure:null }
  ];
  function show(name) { Object.entries(screens).forEach(([key, node]) => node.classList.toggle("hidden", key !== name)); }
  function tone(freq, duration=.12, kind="square") { if(!soundOn)return; audioCtx ||= new (window.AudioContext || window.webkitAudioContext)(); const osc=audioCtx.createOscillator(),gain=audioCtx.createGain(); osc.type=kind;osc.frequency.value=freq;gain.gain.setValueAtTime(.06,audioCtx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+duration);osc.connect(gain).connect(audioCtx.destination);osc.start();osc.stop(audioCtx.currentTime+duration); }
  function startGame() { game={player:{x:355,y:820,dx:0,dy:0},blocks:blocksTemplate.map(x=>({...x,mined:false})),bananas:0,diamonds:0,cake:false,seconds:35,last:0,active:true}; $("bananaCount").textContent="0";$("diamondCount").textContent="0";$("timer").textContent="00:35";$("mineButton").disabled=false;$("gameMessage").textContent="Follow the glowing cracks, then tap MINE. Not every block has treasure!";show("game");tone(440,.1);requestAnimationFrame(loop); }
  function finish(won) { if(!game?.active)return;game.active=false;$("mineButton").disabled=true;if(won){tone(880,.18,"triangle");setTimeout(()=>tone(1100,.25,"triangle"),130);show("reveal")}else{$("gameMessage").textContent="Time's up — but every adventurer is invited!";setTimeout(()=>show("reveal"),800)} }
  function move(direction) { if(!game?.active)return;const speed=28,p=game.player;if(direction==="left")p.dx=-speed;if(direction==="right")p.dx=speed;if(direction==="up")p.dy=-speed;if(direction==="down")p.dy=speed;tone(180,.035,"sine"); }
  function mine() { if(!game?.active)return;const p=game.player,block=game.blocks.find(b=>!b.mined&&Math.hypot(b.x-p.x,b.y-p.y)<72);if(!block){$("gameMessage").textContent="Get closer to a stone block before mining!";tone(170,.08);return}p.x=block.x;p.y=block.y;p.dx=0;p.dy=0;block.mined=true;tone(230,.12);setTimeout(()=>tone(180,.1),80);if(!block.treasure){$("gameMessage").textContent="Just stone! Keep following the glowing cracks.";return}tone(block.treasure==="cake"?660:block.treasure==="diamond"?770:530,.14);if(block.treasure==="banana"){$("bananaCount").textContent=++game.bananas}if(block.treasure==="diamond"){$("diamondCount").textContent=++game.diamonds}if(block.treasure==="cake")game.cake=true;$("gameMessage").textContent=`Treasure found: ${block.treasure==="cake"?"birthday cake":block.treasure}!`;if(game.blocks.every(b=>!b.treasure||b.mined))finish(true); }
  function loop(time) { if(!game?.active)return;const dt=Math.min((time-game.last)/16.67||1,2);game.last=time;const p=game.player;p.x+=p.dx*dt;p.y+=p.dy*dt;p.dx*=.70;p.dy*=.70;p.x=Math.max(28,Math.min(W-28,p.x));p.y=Math.max(70,Math.min(H-28,p.y));const nearby=game.blocks.find(b=>!b.mined&&Math.hypot(b.x-p.x,b.y-p.y)<42);if(nearby){p.x=nearby.x;p.y=nearby.y;p.dx=0;p.dy=0;$("gameMessage").textContent="Lined up! Tap MINE THIS BLOCK."}const seconds=35-Math.floor(time/1000-(game.startedAt||(game.startedAt=time/1000)));if(seconds!==game.seconds&&seconds>=0){game.seconds=seconds;$("timer").textContent=`00:${String(seconds).padStart(2,"0")}`;if(seconds<6)tone(260,.05)}if(seconds<=0)return finish(false);draw(time);requestAnimationFrame(loop); }
  function rect(x,y,w,h,c){ctx.fillStyle=c;ctx.fillRect(x,y,w,h)}
  function drawBlock(b,time){if(b.mined){rect(b.x-34,b.y-34,68,68,"#3f2a27");rect(b.x-25,b.y-25,50,50,"#281b20");ctx.fillStyle="#68402b";ctx.fillRect(b.x-17,b.y-10,13,9);ctx.fillRect(b.x+6,b.y+8,11,8);return}const glow=b.hint&&Math.sin(time/170)>-.25;if(glow){ctx.fillStyle="rgba(82,234,240,.32)";ctx.fillRect(b.x-41,b.y-41,82,82)}rect(b.x-34,b.y-34,68,68,"#6b7078");rect(b.x-27,b.y-27,54,54,"#808890");ctx.strokeStyle=glow?"#7fffff":"#4d535b";ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(b.x-22,b.y-16);ctx.lineTo(b.x-3,b.y-3);ctx.lineTo(b.x-18,b.y+16);ctx.moveTo(b.x+23,b.y-20);ctx.lineTo(b.x+5,b.y+4);ctx.lineTo(b.x+20,b.y+21);ctx.stroke()}
  function draw(time){ctx.clearRect(0,0,W,H);rect(0,0,W,H,"#328bd8");for(let i=0;i<8;i++){rect((i*111+30)%W,80+(i%3)*52,75,20,"#e9f7ff");rect((i*111+52)%W,60+(i%3)*52,35,20,"#e9f7ff")}rect(0,345,W,H-345,"#499748");rect(0,510,W,H-510,"#80502f");for(let x=0;x<W;x+=90)rect(x,520+(x%180?24:0),74,56,"#6f4129");[[60,290],[620,285],[150,445],[510,480]].forEach(([x,y])=>{rect(x,y,28,105,"#6a3e24");rect(x-34,y-60,95,72,"#247343");rect(x-14,y-91,55,43,"#309653")});game.blocks.forEach(b=>drawBlock(b,time));const p=game.player;ctx.save();ctx.translate(p.x,p.y);ctx.fillStyle="#ffd22a";ctx.strokeStyle="#14223f";ctx.lineWidth=7;ctx.beginPath();ctx.roundRect(-27,-39,54,76,21);ctx.fill();ctx.stroke();ctx.fillStyle="#bfc9d0";ctx.fillRect(-30,-21,60,26);ctx.fillStyle="#fff";ctx.beginPath();ctx.arc(-12,-8,12,0,7);ctx.arc(12,-8,12,0,7);ctx.fill();ctx.fillStyle="#15213c";ctx.beginPath();ctx.arc(-9,-8,5,0,7);ctx.arc(9,-8,5,0,7);ctx.fill();ctx.fillStyle="#316db7";ctx.fillRect(-24,17,48,25);ctx.restore() }
  $("startButton").addEventListener("click",()=>{audioCtx ||= new (window.AudioContext||window.webkitAudioContext)();audioCtx.resume?.();startGame()});document.querySelectorAll("[data-direction]").forEach(btn=>btn.addEventListener("pointerdown",e=>{e.preventDefault();move(btn.dataset.direction)}));window.addEventListener("keydown",e=>{const keys={ArrowLeft:"left",ArrowRight:"right",ArrowUp:"up",ArrowDown:"down"};if(keys[e.key]){e.preventDefault();move(keys[e.key])}});$("mineButton").addEventListener("click",mine);$("soundButton").addEventListener("click",()=>{soundOn=!soundOn;$("soundButton").textContent=soundOn?"🔊":"🔇";if(soundOn)tone(440)});$("skipButton").addEventListener("click",()=>finish(true));$("replayButton").addEventListener("click",startGame);
})();
